# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180102_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_head',
            field=models.ImageField(default='wiki/images/peter-pan.jpg', upload_to='wiki/images/'),
        ),
    ]
